[IMP] weni_crm_custom: add new fields
Escodoo/weni-addons pull request #72
Opened 2023-10-06 14:48 UTC by kaynnan

cc @marcelsavegnago

2023-10-09 14:41 UTC, marcelsavegnago commented on weni_crm_custom/models/crm_lead.py
> +    weni_lastSourceAttribution = fields.Char(string="Last Source Attribution")
weni_last_source_attribution

2023-10-09 14:42 UTC, marcelsavegnago commented on weni_crm_custom/models/crm_lead.py
> +    weni_lastSourceAttribution = fields.Char(string="Last Source Attribution")
Tem outros campos que precisa mudar o nome

2023-10-09 14:42 UTC, marcelsavegnago requested changes
Os nomes dos campos estão fora de padrão.

2023-10-09 14:49 UTC, kaynnan commented
Opa, obrigado pela revisão. Ate o fim do dia ajusto a nomenclatura dos campos

2023-10-09 21:37 UTC, kaynnan commented
@marcelsavegnago Creio que agora esteja correto a nomenclatura, alguns pontos fiquei fconfuso tipo o GCLID, mas vi que é um padrão do Google e o FBCLID tbm é uma sigla já resumida

2023-11-09 19:30 UTC, marcelsavegnago approved these changes

2023-11-09 19:42 UTC, merged